[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
merkle_distributor = "7RxH4QMZzH1iuqpvbm4aNF2rHws1tQRReubPRrwhiZuJ"

[programs.localnet]
merkle_distributor = "7RxH4QMZzH1iuqpvbm4aNF2rHws1tQRReubPRrwhiZuJ"

[programs.mainnet]
merkle_distributor = "7RxH4QMZzH1iuqpvbm4aNF2rHws1tQRReubPRrwhiZuJ"

[programs.testnet]
merkle_distributor = "7RxH4QMZzH1iuqpvbm4aNF2rHws1tQRReubPRrwhiZuJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/crisp/.config/solana/id.json"

[workspace]
members = ["programs/merkle-distributor"]

[scripts]
test = "yarn mocha"
